- .github/ISSUE_TEMPLATE/change-request.md
- .github/ISSUE_TEMPLATE/error-report.md
- .github/ISSUE_TEMPLATE/question.md
- .github/pull_request_template.md
Add a PR template and three issue templates.
> .github: add pr and issue templates for docs-dm

- .github/workflows/ci.yaml
- hack/markdown-link-check.tpl
- hack/verify-links.sh
> Add verify links CI check

- .editorconfig
- .github/workflows/media.yml
When you upload files In the `media/` folder, this change can help you sync them to Qiniu bucket and AWS s3 bucket automatically.
> ci: sync media on push

- en/monitor-a-dm-cluster.md
- en/overview.md
- en/precheck.md
- zh/faq.md
- zh/glossary.md
- zh/manage-replication-tasks.md
- zh/skip-or-replace-abnormal-sql-statements.md
1. refine a doc title
2. fix dead links
> zh: refine a doc title and fix dead links

- en/_index.md
- en/overview.md
- zh/_index.md
- zh/overview.md
Add the corresponding relationship between TiDB and DM
> en, zh: add version relation between dm and tidb

- scripts/generate_pdf.sh
> update pdf title

- README.md
Update documentation versions and branch information in README.
> README: update doc versions and branch info

- en/releases/1.0.2.md
- en/releases/1.0.3.md
- en/releases/1.0.4.md
- zh/releases/1.0.2.md
- zh/releases/1.0.3.md
- zh/releases/1.0.4.md
Add `add multi_level_url` to metadata for multi-level-directory files. This is to guarantee the link works well when you click [`Edit this page`](https://pingcap.com/docs/tidb-data-migration/stable/1.0.2/) on the PingCAP website.
> en, zh: add multi_level_url metadata

- .circleci/config.yml
- .markdownlint.yaml
- zh/feature-online-ddl-scheme.md
Signed-off-by: Aylei <rayingecho@gmail.com>
Add markdownlint in CI
close #2
> Add markdownlint check in CI

- en/feature-overview.md
The explanation for dm black white list is not clear. So add more explanation.
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/31
> en: add more explanation in feature-overview.md

- zh/manage-replication-tasks.md
update manage-replication-tasks.md for 2.0
- Other reference link(s): 
preview: https://github.com/GMHDBJD/docs-dm/blob/manage-replication-tasks-2.0/zh/manage-replication-tasks.md
> zh: update manage-replication-tasks.md for 2.0

- .github/workflows/ci.yaml
- .markdownlint.yaml
- en/overview.md
Run markdownlint in github actions
- Other reference link(s): https://github.com/pingcap/docs-dm/pull/40
> run markdownlint in github actions

- zh/monitor-a-dm-cluster.md
Update monitor-a-dm-cluster.md for 2.0 from [dm.json](https://github.com/pingcap/dm/blob/master/dm/dm-ansible/scripts/dm.json)
- Other reference link(s): 
preview: https://github.com/GMHDBJD/docs-dm/blob/monitor-a-dm-cluster-2.0/zh/monitor-a-dm-cluster.md
> zh: update monitor-a-dm-cluster.md for 2.0

- en/overview.md
update image link in overview.md
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/30
> en: update overview.md for 2.0

- en/dm-master-configuration-file.md
- en/dm-worker-configuration-file.md
Update the wording of DM-worker and DM-master config files.
- Other reference link(s):  https://github.com/pingcap/docs-dm/pull/34 https://github.com/pingcap/docs-dm/pull/36
> en: update the wording of dm-worker & dm-master config files

- en/TOC.md
- en/releases/1.0.5.md
- zh/TOC.md
- zh/releases/1.0.5.md
> release: add release notes for v1.0.5

- en/task-configuration-file.md
Add an example of updating task config.
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/43
> en: add config change example

- .github/workflows/media.yml
> ci: update media.yml

- en/config-overview.md
- en/dm-worker-intro.md
- en/feature-overview.md
- zh/config-overview.md
- zh/dm-worker-intro.md
- zh/feature-overview.md
The breaking line misses the closing tag. Change `<br>` to `<br/>`
> fix: add closing tag for 'br'

- scripts/markdownlint
Add a script to run markdownlint check locally.
> scripts: add a script to run markdownlint check locally

- .github/workflows/ci.yaml
> trigger pull request CI on all branches

- .github/workflows/ci.yaml
change the branch scope of the CI check
- Other reference link(s):  https://github.com/pingcap/docs-dm/pull/82
> ci.yaml: change the branch scope of the CI check

- en/cluster-operations.md
> en: add draft false

- zh/_index.md
> Update landing page _index.md for TiDB DM

- zh/faq.md
add FAQ about adding tables to existing task
> zh: add FAQ about adding tables to existing task

- en/TOC.md
- en/releases/1.0.6.md
- zh/TOC.md
- zh/releases/1.0.6.md
add release notes for DM v1.0.6
> *: add release notes for v1.0.6

- en/task-configuration-file-full.md
- zh/task-configuration-file-full.md
- change comment of password config
- add session config
- add enable-ansi-quotes config
> *: update docs about task config

- en/_index.md
- en/deploy-a-dm-cluster-using-binary.md
- en/online-ddl-scheme.md
- zh/TOC.md
- zh/_index.md
- Update `_index.md` with the [new landing page format](https://github.com/pingcap/website-docs#landing-page-for-tidb)
- Update descriptions of some topics and lists
- This PR is translated from: #101 
> en, zh: update en index and zh list

- .github/assign-by-files.yml
- .github/workflows/auto-assign.yml
- en/benchmark-v1-alpha.md
> add auto assign reviewers github action

- en/_index.md
- Other reference link(s): 1.0 has been modified in https://github.com/pingcap/docs-dm/pull/127/
> Remove _index/ in the alias

- en/deploy-a-dm-cluster-using-ansible.md
- zh/overview.md
- zh/relay-log.md
add aliases to fix 404 errors in docs/blogs
> *: add aliases to support early links

- en/create-task-and-verify.md
- en/daily-check.md
- en/hardware-and-software-requirements.md
Added aliases to files that are newly added since Jun 25
1.0: no new file since Jun 25
> add 3 aliases to 3 files to avoid 404 urls in Google

- en/feature-manually-handling-sharding-ddl-locks.md
> en: fix wrong section number (#147)

- en/task-configuration-file-full.md
- zh/task-configuration-file-full.md
Add missing `case-sensitive` config for task.
> zh, en: add missing task config

- .circleci/config.yml
> chore: update PDF name

- zh/handle-performance-issues.md
fix two bugs about handling performance issues
- This PR is translated in: https://github.com/pingcap/docs-dm/pull/142
> zh: fix two bugs in handle-performance-issues.md

- .github/workflows/auto-assign.yml
- .github/workflows/auto-label.yml
Disabled 2 github actions because github actions won't work for PRs filed from forked repos, thus violating our standard procedures of sending PRs to upstream.
> disable 2 github actions

- zh/task-configuration-file-full.md
add configuration introduced by https://github.com/pingcap/dm/pull/770
- Other reference link(s):https://github.com/pingcap/dm/pull/770
> zh: add `clean-dump-file` configuration (dev)

- zh/manage-source.md
add description introduced by https://github.com/pingcap/dm/pull/779
- Other reference link(s):https://github.com/pingcap/dm/pull/779
> zh: support multiple sources create/stop

- zh/task-configuration-file-full.md
> an: fix dead link

- zh/usage-scenario-simple-replication.md
> zh: Add an alias to fix dead link

- zh/config-overview.md
- zh/precheck.md
- zh/task-configuration-file-full.md
add description of task config `ignore-checking-items`, part of https://github.com/pingcap/dm/issues/200
- Other reference link(s): https://github.com/pingcap/dm/issues/200
> zh: add description of task config `ignore-checking-items`

- en/task-configuration-file-full.md
add configuration introduced by pingcap/dm#804
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/170, https://github.com/pingcap/docs-dm/pull/169
> en: add `clean-dump-file` configuration

- zh/precheck.md
- zh/task-configuration-file-full.md
> zh: add description of task config `ignore-checking-items` (#177)

- en/deploy-a-dm-cluster-using-ansible.md
https://asktug.com/t/topic/35036
已经复现。
密码形式为：abc(字符)@(特殊字符)123(数字)
如果不加引号加密，task 将会报错。
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/105
> en: add quote to special characters

- zh/config-overview.md
- zh/manage-source.md
- zh/precheck.md
- zh/quick-start-create-task.md
- zh/source-configuration-file.md
- zh/task-configuration-file-full.md
accroding to https://github.com/pingcap/dm/pull/828, update source configuration to YAML
> update source configuration to YAML

- en/TOC.md
- en/_index.md
- en/faq.md
- en/feature-online-ddl-scheme.md
- en/key-features.md
- en/scenarios.md
- en/task-configuration-file-full.md
- zh/task-configuration-file-full.md
- rename `online-ddl-scheme.md` to `feature-online-ddl-scheme.md`
- minor edit `task-configuration-file-full.md`
- Other reference link(s):https://github.com/pingcap/docs-dm/pull/143
> *: rename a doc

- en/key-features.md
- zh/key-features.md
[2020/07/29 16:24:42.149 +08:00] [ERROR] [heartbeat.go:256] [“update heartbeat ts”] [component=heartbeat] [error="[code=10001:class=database:scope=upstream:level=high] database driver error: Error 1142: DELETE command denied to user ‘dm_worker’@‘172.16.120.7’ for table ‘heartbeat’"]
> zh, en: Add a privilege for`enable-heartbeat`

- .github/pull_request_template.md
Signed-off-by: Ran <huangran@pingcap.com>
> .github: add cherry-pick checklist in pr template

- en/cluster-operations.md
- en/manage-replication-tasks.md
- en/table-selector.md
Add 3 aliases to fix 3 dead links
> en: add 3 aliases to fix 3 dead links

- zh/releases/1.0.4.md
Fix an alias to fix a dead link.
> Fix a deadlink in dm doc

- zh/releases/1.0.4.md
> Fix a typo in alias

- zh/deploy-a-dm-cluster-using-binary.md
Close https://github.com/pingcap/docs/issues/3156, DM should manage the download link by itself.
- Other reference link(s): https://docs.pingcap.com/zh/tidb/stable/download-ecosystem-tools
> zh: update download

- zh/dmctl-introduction.md
- zh/manage-source.md
add `operate-source show`
- Other reference link(s): https://github.com/pingcap/dm/pull/838
> add `operate-source show`

- en/benchmark-v1.0-ga.md
- en/error-handling.md
- en/usage-scenario-shard-merge.md
- zh/benchmark-v1.0-ga.md
- zh/error-handling.md
Add 5 links to fix dead links.
> en, zh: add 5 links to fix dead links

- en/dm-worker-configuration-file-full.md
- en/error-handling.md
- en/faq.md
- en/relay-log.md
update the FAQ about reset task
clarify the purge-expires config item
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/104
- Other reference link(s): the same purpose as #103
> 1.0: update docs about reset task and relay log purge

- en/TOC.md
- en/error-handling.md
- Add `workaround` for the error system
- Some minor updates
- This PR is translated from: #243
> en: update error handling descriptions

- en/TOC.md
- en/enable-tls.md
- en/generate-self-signed-certificates.md
+ Most majority of the content in *Enable TLS for DM Connections* is reused from [Enable TLS Between TiDB Components](https://docs.pingcap.com/tidb/dev/enable-tls-between-components).
+ Most majority of the content in *Generate Self-signed Certificates* is reused from [Generate Self-signed Certificates](https://docs.pingcap.com/tidb/dev/generate-self-signed-certificates).
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/233
> en: add security-related documents

- en/releases/1.0.2.md
- en/releases/1.0.3.md
- en/releases/1.0.4.md
- en/releases/1.0.5.md
- en/releases/1.0.6.md
- zh/releases/1.0.2.md
- zh/releases/1.0.3.md
- zh/releases/1.0.4.md
- zh/releases/1.0.5.md
- zh/releases/1.0.6.md
> Remove deprecated multi_level_url meta

- .circleci/config.yml
Filter branch to generate PDF for v2.0
> chore: update PDF generator

- en/manage-source.md
add description introduced by https://github.com/pingcap/docs-dm/pull/779
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/171
- Other reference link(s): https://github.com/pingcap/docs-dm/pull/779
> en: support multiple sources create/stop

- en/precheck.md
- en/task-configuration-file-full.md
add a description of task config `ignore-checking-items`, part of https://github.com/pingcap/docs-dm/pull/200
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/177
- Other reference link(s): https://github.com/pingcap/docs-dm/pull/200
> en: add description of task config `ignore-checking-items`

- zh/replicate-data-using-dm.md
enable-gtid: false
change to
enable-gtid: true
Describe
> Update enable-gtid description

- en/create-task.md
- en/feature-online-ddl-scheme.md
- en/overview.md
- en/task-configuration-file-full.md
- en/task-configuration-file.md
- en/usage-scenario-shard-merge.md
- en/usage-scenario-simple-replication.md
- zh/create-task.md
- zh/feature-online-ddl-scheme.md
- zh/overview.md
- zh/task-configuration-file-full.md
- zh/task-configuration-file.md
- zh/usage-scenario-shard-merge.md
- zh/usage-scenario-simple-replication.md
- remove `remove-meta` item in task config
- add `remove-meta` flag for `start-task`
> *: update `remove-meta`

- zh/maintain-dm-using-tiup.md
> Add warning for import cmd

- zh/maintain-dm-using-tiup.md
- add notices about import/scale with TiUP
- fix some wording
> zh: add notices about import/scale with TiUP; some mirror fix

- zh/_index.md
- zh/overview.md
> zh: add a simpe desc about HA

- en/dm-upgrade.md
- en/feature-manually-handling-sharding-ddl-locks.md
- en/feature-shard-merge.md
- en/query-status.md
- en/table-selector.md
- zh/cluster-operations.md
- zh/dm-master-configuration-file.md
- zh/error-handling.md
- zh/faq.md
- zh/feature-manually-handling-sharding-ddl-locks.md
- zh/feature-overview.md
- zh/skip-or-replace-abnormal-sql-statements.md
- zh/table-selector.md
- zh/usage-scenario-master-slave-switch.md
Add 14 aliases to fix dead links
> Add 14 aliases to fix dead links

- en/dm-worker-configuration-file.md
`join` is used in `etcdutil.CreateClient` where needs endpoint, which should be URLs
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/303
> en: update join config

- zh/deploy-a-dm-cluster-using-binary.md
- zh/deploy-a-dm-cluster-using-tiup.md
- zh/maintain-dm-using-tiup.md
add some notices about connectivity
> zh: add some notices about connectivity

- en/overview.md
- en/task-configuration-file-full.md
- zh/manage-replication-tasks.md
- zh/releases/1.0.5.md
Add 4 aliases to fix dead links.
> Add 4 aliases to fix dead links

- en/source-configuration-file.md
- en/task-configuration-file-full.md
- zh/source-configuration-file.md
- zh/task-configuration-file-full.md
- refine comments for `enable-gtid: false`
- add `binlog-gtid` for task config
> *: refine docs about binlog GTID

- en/cluster-operations.md
- en/glossary.md
- en/usage-scenario-simple-replication.md
- zh/releases/1.0.2.md
- zh/releases/1.0.5.md
- zh/task-configuration-file.md
- zh/usage-scenario-simple-replication.md
Add 7 aliases to fix dead links.
> Add 7 aliases to fix dead links

- en/maintain-dm-using-tiup.md
add a notice about topology example for scale-out via TiUP.
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/348
> en: add a notice about topology example for scale-out

- en/quick-start-create-task.md
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/296
> Add hints for using plaintext passwords

- en/migrate-from-mysql-aurora.md
- zh/migrate-from-mysql-aurora.md
remove some limit to track https://github.com/pingcap/dm/pull/988
- Other reference link(s): https://github.com/pingcap/dm/pull/988
> zh, en: update Aurora migration doc

- en/deploy-a-dm-cluster-using-tiup.md
- en/faq.md
add two question
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/350
> en: update some steps to resolve problems

- en/task-configuration-file-full.md
- zh/task-configuration-file-full.md
there're two `ignore-checking-items: []` in example config, so remove one (remove first one that seems older)
> zh, en: remove duplicate config item

- zh/deploy-a-dm-cluster-using-binary.md
- zh/deploy-a-dm-cluster-using-tiup.md
- zh/handle-failed-sql-statements.md
- zh/task-configuration-file-full.md
- zh/task-configuration-file.md
- 推荐使用 TiUP 部署 DM 集群
- 完善 `handle-error` 时的 binlog position 获取方式
- 完善 `handle-error` 在合库合表时的上游分表情况说明
- 完善多实例数据迁移时并发控制参数的说明
> zh: refine some docs

- zh/deploy-a-dm-cluster-using-binary.md
- zh/deploy-a-dm-cluster-using-tiup-offline.md
- zh/deploy-a-dm-cluster-using-tiup.md
`如果不需要确保 DM 集群高可用，则可只部署 1 个 DM-master 节点、不少于上游待迁移的 MySQL/MariaDB 实例数的 DM-worker 节点。`
> zh: clarify required members number

- zh/feature-shard-merge-optimistic.md
- zh/feature-shard-merge-pessimistic.md
add more restrictions for shard support
> zh: add more restrictions for shard support

- en/deploy-a-dm-cluster-using-binary.md
- en/deploy-a-dm-cluster-using-tiup-offline.md
- en/deploy-a-dm-cluster-using-tiup.md
- zh/deploy-a-dm-cluster-using-binary.md
Update dm cluster deploy files.
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/403
> en: clarify required members number

- zh/deploy-a-dm-cluster-using-tiup.md
> zh: Update deploy-a-dm-cluster-using-tiup.md

- zh/task-configuration-file-full.md
`--no-lock` change to `--consistency none`
Because dumpling replaced mydumper in dm 2.0
> zh: update Dumpling configure

- zh/get-started.md
> 1.0: fix dead link

- en/get-started.md
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/431
> 1.0 en: fix dead link

- en/_index.md
> test cherry-picker bot

- en/faq.md
- zh/faq.md
> zh, en: update a FAQ

- zh/task-configuration-file-full.md
align with https://github.com/pingcap/dm/pull/1032
- Other reference link(s): https://github.com/pingcap/dm/pull/1032
> zh: update target settings in config file

- en/feature-shard-merge-optimistic.md
- zh/feature-shard-merge-optimistic.md
add an unsupported optimistic shard DDL statement
> *: add an unsupported optimistic shard DDL statement

- en/glossary.md
- en/migrate-from-mysql-aurora.md
Add some description about "safe mode".
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/444
> en: update safe mode description

- en/maintain-dm-using-tiup.md
- zh/maintain-dm-using-tiup.md
add a note for importing from v1.0
> *: add a note for importing from v1.0

- en/task-configuration-file-full.md
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/445
> en: update target settings in config file

- en/cluster-operations.md
- en/deploy-a-dm-cluster-using-ansible.md
- en/dm-portal.md
- en/dm-upgrade.md
- en/feature-manually-handling-sharding-ddl-locks.md
- en/feature-overview.md
- en/get-started.md
- en/manage-migration-tasks.md
- en/skip-or-replace-abnormal-sql-statements.md
- en/task-configuration-file-full.md
- zh/cluster-operations.md
- zh/deploy-a-dm-cluster-using-ansible.md
- zh/dm-portal.md
- zh/dm-upgrade.md
- zh/feature-manually-handling-sharding-ddl-locks.md
- zh/feature-overview.md
- zh/get-started.md
- zh/manage-migration-tasks.md
- zh/skip-or-replace-abnormal-sql-statements.md
- zh/task-configuration-file-full.md
add stable aliases to 1.0 files that don't exist on 2.0 or above
> zh, en: add stable aliases to 1.0 files that don't exist on 2.0 or above

- README.md
Migrate changes in https://github.com/pingcap/docs-dm/pull/423. Add google translate links for Indonesian and Japanese languages.
- Other reference link(s): https://github.com/pingcap/docs-dm/pull/423
> en: add google translate links in readme

- .github/workflows/stale.yml
Signed-off-by: Ran <huangran@pingcap.com>
Add an action to check stale issues.
> .github: add an action to check stale issues

- en/monitor-a-dm-cluster.md
- en/precheck.md
- zh/dm-worker-configuration-file.md
- zh/error-handling.md
- zh/migrate-from-mysql-aurora.md
Add 5 aliases to fix broken links
> Add 5 aliases to fix broken links

- en/manage-migration-tasks.md
- zh/deploy-a-dm-cluster-using-ansible.md
- zh/dm-upgrade.md
- zh/dm-worker-configuration-file.md
Add 4 aliases to fix broken links.
> Add 4 aliases to fix broken links

- en/feature-overview.md
- zh/feature-overview.md
remove a notice for column-mapping because column-mapping is not recommended.
> *: remove a notice for column-mapping

- README.md
Add Google Translate links of French and Korean to the README file.
> readme: add google translate links of French and Korean

- .github/pull_request_template.md
Add CLA signing request in the pull request template and simplify the content.
> add CLA signing guide

- en/faq.md
Add three items in `faq.md`
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/505
> en: add three items in faq.md

- en/error-handling.md
- en/task-configuration-file.md
- zh/quick-start-with-dm.md
Add 3 aliases to fix broken links.
> Add 3 aliases to fix broken links

- zh/glossary.md
- Other reference link(s): https://github.com/pingcap/tidb-enterprise-tools/pull/470
> Add a case of safe-mode enabled

- en/faq.md
Update FAQ in last week oncall. Add three FAQs.
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/510
> en: Update faq.md

- zh/faq.md
> *: add some faq

- en/TOC.md
- en/releases/2.0.1.md
- zh/TOC.md
- zh/releases/2.0.1.md
> zh,en: add release notes for 2.0.1

- en/precheck.md
- zh/precheck.md
update precheck items for v2.0.1
https://github.com/pingcap/dm/pull/1315
> zh,en: update precheck items

- en/glossary.md
Add a case of safe-mode being enabled.
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/513
> en: add a case of safe-mode being enabled

- en/command-line-flags.md
- zh/command-line-flags.md
> *: fix examples for initial-cluster

- en/overview.md
- zh/overview.md
- Other reference link(s): https://github.com/pingcap/docs/pull/4542, https://github.com/pingcap/docs-cn/pull/5213
> Add syncer alias

- en/faq.md
Add 2 FAQs and update 1 FAQ.
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/523
> en: add 2 faqs and update 1 faq

- .github/workflows/stale.yml
Use the latest version and modify 2 configs
- Other reference link(s):https://github.com/pingcap/docs/pull/4673
> .github: update stale action version

- zh/dmctl-introduction.md
- zh/faq.md
- zh/source-configuration-file.md
> faq: update dm docs and faq

- zh/task-configuration-file.md
Add get-config related information and application scenarios in the document
> Check steps after adding and modifying

- zh/manage-source.md
Increase the inspection steps after operating-source is successful，
> Increase the inspection steps after operating-source is successful

- en/quick-start-create-task.md
- zh/quick-start-create-task.md
Signed-off-by: Yujie Xia <xiayjchn@gmail.com>
Fix incorrect SQL statements in quick-start-create-task.md.
> Fix incorrect SQL statements in quick-start-create-task.md

- en/manage-source.md
- en/task-configuration-file.md
Add information and application scenarios of the `get-config` command in the document.
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/552, https://github.com/pingcap/docs-dm/pull/553
> en: add information of the `get-config` command

- zh/dm-arch.md
- zh/quick-start-with-dm.md
- zh/task-configuration-guide.md
- zh/usage-scenario-shard-merge.md
This PR is an implement of https://github.com/pingcap/docs-dm/pull/557. Some terminologies are changed in this PR.
> refine dm docs structure

- zh/faq.md
> zh: update faq from oncall issue

- en/feature-manually-handling-sharding-ddl-locks.md
Change `unlock-dll-lock` to `unlock-ddl-lock`.
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/596
> en: fix a typo in feature-manually-handling-sharding-ddl-locks.md

- en/feature-shard-merge-pessimistic.md
- zh/feature-shard-merge-pessimistic.md
In fact DM treats all sources in a task as a sharding group.
- Other reference link(s): close https://github.com/pingcap/dm/issues/1517
> adjust some limitation about sharding ddl

- en/deploy-a-dm-cluster-using-tiup-offline.md
- en/deploy-a-dm-cluster-using-tiup.md
- en/maintain-dm-using-tiup.md
Fix dead external links found in https://github.com/pingcap/docs-dm/pull/605#issuecomment-816370389.
> en: fix dead external links

- en/TOC.md
- en/releases/2.0.2.md
- zh/TOC.md
- zh/releases/2.0.2.md
> [2.0.2] *: update release note

- en/releases/2.0.2.md
forget a space (no hurry to merge)
> *: fix a missing space

- zh/deploy-a-dm-cluster-using-tiup.md
after deploy DM cluster, guide user to obtain `dmctl`
> guide user to dmctl

- en/deploy-a-dm-cluster-using-binary.md
- zh/deploy-a-dm-cluster-using-binary.md
- Other reference link(s): some comments from https://github.com/pingcap/dm/issues/1431
> *: add constraint for binary deployment

- en/faq.md
- en/source-configuration-file.md
Update dm docs and add 4 FAQs.
The changes in `zh/dmctl-introduction.md` have been partly aligned to `en/dmctl-introduction.md` in https://github.com/pingcap/docs-dm/pull/560. Confirmed with @lance6716 that he will align the rest changes when DM v2.0.2 is about to release. 
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/551
- Other reference link(s): https://github.com/pingcap/docs-dm/pull/560
> faq: update dm docs and add 4 FAQs

- en/migrate-data-using-dm.md
- en/overview.md
- en/precheck.md
1. Update info about MySQL 8.0 support
2. Link to the precheck info in `migrate-data-using-dm` earlier to make
sure the user has information about required privileges when needed.
> Update precheck info about MySQL 8.0 support

- zh/migrate-data-using-dm.md
Do not need to describe the details of the small version of V1 in the documentation of V2
> Update description for `extra-args`

- zh/task-configuration-file-full.md
> Remove skip-tz-utc parameter

- zh/usage-scenario-shard-merge.md
> Remove the skip-tz-utc configuration item

- en/faq.md
Update  2 FAQs from oncall issue.
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/594
> en: update  2 FAQs from oncall issue

- zh/faq.md
Refine the description of one FAQ.
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/593#discussion_r612299902
> zh: refine the description of one faq

- en/deploy-a-dm-cluster-using-binary.md
- en/deploy-a-dm-cluster-using-tiup.md
- zh/deploy-a-dm-cluster-using-binary.md
- zh/deploy-a-dm-cluster-using-tiup.md
- zh/quick-start-with-dm.md
add shortcuts to generate dm template
> *: update docs-dm

- en/deploy-a-dm-cluster-using-tiup-offline.md
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/650
> en: update deploy-a-dm-cluster-using-tiup-offline.md

- en/TOC.md
- en/releases/2.0.2.md
- en/releases/2.0.3.md
- zh/TOC.md
- zh/releases/2.0.2.md
- zh/releases/2.0.3.md
> [2.0.3] *: update release note

- en/dmctl-introduction.md
- zh/dmctl-introduction.md
> zh,en: update dmctl commands for v2.0.3

- en/deploy-a-dm-cluster-using-tiup.md
Guide users to get `dmctl` after they deploy DM clusters.
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/603
> en: guide user to get dmctl

- en/TOC.md
- zh/TOC.md
add `deploy dm in k8s` link to toc
- https://docs.pingcap.com/zh/tidb-in-kubernetes/dev/deploy-tidb-dm
> *: add link: deploy dm in k8s

- en/source-configuration-file.md
Add a description of the requirement of security config in source-configuration file.md to close #607.
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/655
> en: update security config requirement in source configuration file

- zh/quick-start-with-dm.md
fix testdm-task.yaml format in quick-start-with-dm.md
fix the format of testdm-task.yaml to ensure the related command work
> zh: fix testdm-task.yaml format

- en/quick-start-with-dm.md
fix testdm-task.yaml format in quick-start-with-dm.md
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/674
> en: fix testdm-task.yaml format

- en/deploy-a-dm-cluster-using-tiup-offline.md
- en/deploy-a-dm-cluster-using-tiup.md
- en/maintain-dm-using-tiup.md
- zh/deploy-a-dm-cluster-using-tiup-offline.md
- zh/deploy-a-dm-cluster-using-tiup.md
- zh/maintain-dm-using-tiup.md
Update the patch version numbers to the latest.
> *: update patch version to the latest

- en/TOC.md
Add a missing indent in English TOC to fix abnormal display.
> en: add a missing indent in English TOC to fix abnormal display

- en/quick-start-create-task.md
- en/task-configuration-file-full.md
- en/task-configuration-guide.md
- en/usage-scenario-shard-merge.md
- zh/task-configuration-file-full.md
- zh/task-configuration-guide.md
- zh/usage-scenario-shard-merge.md
Fix yaml indent issues to close https://github.com/pingcap/docs-dm/issues/676.
> *: fix yaml indent issues

- en/relay-log.md
- en/source-configuration-file.md
- zh/relay-log.md
- zh/source-configuration-file.md
- add `relay-dir` config item for source-configuration-file
- update some relay description
> zh, en: add relay-dir for source-configuration-file

- zh/overview.md
add some introduction in overview.md
> zh: add some introduction in `overview.md`

- CONTRIBUTING.md
- README.md
- Add `Contributing` section to readme
- Add contributing guide file
> readme: add contributing guide

- en/dmctl-introduction.md
- en/enable-tls.md
- en/quick-start-create-task.md
- en/quick-start-with-dm.md
- zh/dmctl-introduction.md
- zh/enable-tls.md
- zh/quick-start-create-source.md
- zh/quick-start-create-task.md
- zh/quick-start-with-dm.md
Update manual about dmctl for the changes made in https://github.com/pingcap/dm/pull/1750
> *: update dmctl document about usage

- en/TOC.md
- en/releases/2.0.4.md
- zh/TOC.md
- zh/releases/2.0.4.md
> zh, en: add 2.0.4 release note

- en/TOC.md
- en/releases/1.0.7.md
- zh/TOC.md
- zh/releases/1.0.7.md
> zh, en: update release note for v1.0.7

- en/dmctl-introduction.md
- zh/dmctl-introduction.md
The env var $DM_MASTER_ADDR was wrongly written as $DM_MASTER_ADD in an example code.
> dmctl-introducation: fix typo

- en/deploy-a-dm-cluster-using-binary.md
- zh/deploy-a-dm-cluster-using-binary.md
Specify an ip for master addr in configuration. Or we will get an error like:
```
parse cmd flags err: master-addr (:8261) must include the 'host' part (should not be '0.0.0.0') when advertise-addr is not set
```
> Specify an ip for master addr in configuration

- .github/pull_request_template.md
Optimize the description of the master branch in the PR template.
- Other reference link(s): https://github.com/pingcap/docs-dm/pull/688#discussion_r638472346
> PR template: Optimize description of the master branch in the PR template

- zh/TOC.md
- zh/dmctl-introduction.md
- zh/export-import-config.md
- zh/maintain-dm-using-tiup.md
> zh: add config command for v2.0.5

- en/TOC.md
- en/dmctl-introduction.md
- en/export-import-config.md
- en/maintain-dm-using-tiup.md
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/736
> [2.0.5] en: add config command for v2.0.5

- en/TOC.md
- en/releases/2.0.5.md
- zh/TOC.md
- zh/releases/2.0.5.md
> zh, en: update release note for v2.0.5

- hack/verify-link-anchors.sh
> chore: lock lint plugin versions

- en/TOC.md
- en/deploy-a-dm-cluster-using-tiup-offline.md
- en/deploy-a-dm-cluster-using-tiup.md
- en/maintain-dm-using-tiup.md
- en/releases/2.0.6.md
- zh/TOC.md
- zh/deploy-a-dm-cluster-using-tiup-offline.md
- zh/deploy-a-dm-cluster-using-tiup.md
- zh/maintain-dm-using-tiup.md
- zh/releases/2.0.6.md
> zh, en: update release note for v2.0.6

- en/faq.md
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/723
> faq.md: add proxy question

- zh/monitor-a-dm-cluster.md
- This PR is translated from: https://github.com/pingcap/dm/pull/1778/
> add more metrics

- .github/workflows/ci.yaml
Fix an error that check-tags.py never actually worked. (For details, see https://github.com/CharLotteiu/pingcap-docs-checks/issues/5)
The error is found in blog, docs-tidb-operator, and docs-dm.
> .github: fix github action config

- .circleci/config.yml
The markdown lint check in Circleci is duplicated in git action workflow, so remove lint check from circleci.
> chore: remove markdown lint from circleci

- en/monitor-a-dm-cluster.md
- zh/monitor-a-dm-cluster.md
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/756
> monitor-a-dm-cluster: add more metrics

- zh/deploy-a-dm-cluster-using-tiup-offline.md
> Corrected a typo

- zh/task-configuration-file-full.md
> Optimize the annotation of worker-size to avoid ambiguity

- en/releases/2.0.7.md
- zh/releases/2.0.7.md
> zh, en: update release note for v2.0.7

- en/TOC.md
- zh/TOC.md
> zh,en: update release note 2.0.7

- en/faq.md
- zh/faq.md
> faq.md: add 1 FAQ

- .github/pull_request_template.md
- .github/workflows/dispatch.yml
chore: stop building temporary
> chore: stop building temporary

- en/TOC.md
- en/open-api.md
- zh/open-api.md
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/812
> en: add OpenAPI docs

- en/open-api.md
- zh/open-api.md
> *: fix openapi json example

- zh/TOC.md
TOC style failed caused by incorrect format
> chore: update TOC format

- .github/workflows/ci.yaml
- .github/workflows/dispatch.yml
Update CI config in release-5.3
@Liuxiaozhen12 Please DO NOT merge this PR unless @YiniXu9506 allows you to do so.
> chore: update CI config in release-5.3

- en/TOC.md
- en/_index.md
- en/releases/5.3.0.md
- zh/TOC.md
- zh/_index.md
- zh/releases/5.3.0.md
Refine description in dm index page
> Refine description in dm index page

- en/TOC.md
> Fix format in TOC

- zh/overview.md
Replaced a video for the overview page
> replace a video for the overview page

- zh/relay-log.md
- zh/source-configuration-file.md
> update description of relay log

- en/_index.md
- en/deploy-a-dm-cluster-using-binary.md
- en/faq.md
- en/open-api.md
- en/releases/5.3.0.md
- zh/_index.md
- zh/deploy-a-dm-cluster-using-binary.md
- zh/faq.md
- zh/open-api.md
- zh/releases/5.3.0.md
changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
> changed github.com/pingcap/ticdc to github.com/pingcap/tiflow

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
This PRs adds the information about the DM doc master branch changes to the PR template, the Readme file, and the contribution guide. 
> repository: add information about the DM doc master branch changes 

- en/get-started.md
- zh/get-started.md
Signed-off-by: hi-rustin <rustin.liu@gmail.com>
Remove unknown dir config
None
None
> Remove unknown dir config

- en/task-configuration-file-full.md
- zh/task-configuration-file-full.md
- Other reference link(s): Cherry-pick from https://github.com/pingcap/docs-cn/pull/8159
> adjust timezone config description

- en/TOC.md
- [z] I've signed [**Contributor License Agreement**](https://cla-assistant.io/pingcap/docs-dm) that's required for repo owners to accept my contribution.
> list format in TOC

- en/dm-benchmark-v5.3.0.md
- zh/dm-benchmark-v5.3.0.md
To fix 404 caused by removing dm 5.3 benchmark report from docs-cn and docs repos.
> add aliases to 5.3 dm benchmark report

- .github/workflows/ci.yaml
Close https://github.com/pingcap/docs-dm/issues/910
> ci: update node version to 16
