- en/feature-overview.md
- zh/feature-overview.md
Fix version for black-white list.
In https://github.com/pingcap/docs-cn/pull/2383 we set support wildcard version to v1.0.4. Actually it's v1.0.5.
https://github.com/pingcap/dm/pull/515 only update the master branch but isn't cherry-picked to release-1.0. Actually this is supported from v1.0.5.
https://github.com/pingcap/dm/pull/632
> en, zh: address version support

- zh/deploy-a-dm-cluster-using-ansible.md
https://asktug.com/t/topic/35036
已经复现。
密码形式为：abc(字符)@(特殊字符)123(数字)
如果不加引号加密，task 将会报错。
"msg": "[code=10001:class=dump-unit:scope=upstream:level=high] fail to initial unit Dump of subtask qh : database driver error: Error 1045: Access denied for user 'qh_test'@'172.16.5.169' (using password: YES)\n
> zh: frame special characters with quotes to ensure encryption correctness

- zh/TOC.md
- zh/error-handling.md
1. mv dm-portal to config
2. add error handling about load, similar with https://github.com/pingcap/docs-cn/pull/3655, https://github.com/pingcap/docs-cn/blob/532f7458f6668da6bfd536132550d0ec7ea708b8/load-misuse-handling.md this file will be deleted, so move the content to dm's error-handling.md
> zh: update TOC and error-handling.md

- zh/task-configuration-file-full.md
add configuration introduced by https://github.com/pingcap/dm/pull/804
https://github.com/pingcap/dm/pull/804
> zh: add `clean-dump-file` configuration (release-1.0)

- en/dm-master-configuration-file.md
- en/dm-worker-configuration-file.md
- en/source-configuration-file.md
- en/task-configuration-file-full.md
- zh/dm-master-configuration-file.md
- zh/dm-worker-configuration-file.md
- zh/source-configuration-file.md
- zh/task-configuration-file-full.md
add tls config in source config file and task config file.
> zh,en: update tls config

- en/migrate-from-mysql-aurora.md
- zh/migrate-from-mysql-aurora.md
removed wrong guide because other consistency than `--consistency none` is always unabled.
> zh, en: remove improper guide

- zh/dm-worker-configuration-file.md
`join` is used in `etcdutil.CreateClient` where needs endpoint, which should be URLs
> zh: update join config

- en/command-line-flags.md
- zh/command-line-flags.md
modify format of --advertise-peer-urls to align with pingcap/dm#955
> zh, en: modify format of `--advertise-peer-urls` (master)

- .github/workflows/link-check.yaml
add `exit_code` check for external link check on `zh`.
> *: add exit_code check for zh link checking

- en/dm-worker-intro.md
- en/glossary.md
- en/key-features.md
- en/overview.md
- en/task-configuration-file-full.md
- update some links to MySQL docs because `slave` has been updated
- add more explanation about HA
- add `max-allowed-packet` into task config sample
- mirror updates the format about TiUP doc
- This PR is translated from: https://github.com/pingcap/docs-dm/pull/379
> en: some mirror updates 

- en/TOC.md
- en/_index.md
- en/faq.md
- en/handle-failed-ddl-statements.md
- en/overview.md
- zh/TOC.md
- zh/_index.md
- zh/faq.md
- zh/handle-failed-ddl-statements.md
- zh/overview.md
Update handle-error command description for v2.0.1
Now handle-error only support ddl statement.
https://github.com/pingcap/dm/pull/1303
> zh,en: change `sql` to `DDL` for handle-error command

- en/config-overview.md
- en/manage-source.md
- en/manually-upgrade-dm-1.0-to-2.0.md
- en/performance-test.md
- zh/TOC.md
- zh/config-overview.md
- zh/manage-source.md
- zh/manually-upgrade-dm-1.0-to-2.0.md
- zh/performance-test.md
- zh/task-configuration-guide.md
align with https://github.com/pingcap/dm/pull/1492
> [2.0.2] *: add `transfer-source` command

- en/quick-start-create-task.md
- zh/quick-start-create-task.md
- Other reference link(s): some comments from https://github.com/pingcap/dm/issues/1431
> *: update tidb-server download URL

- zh/usage-scenario-simple-migration.md
dumpling does not have this parameter, the current behavior is skip-tz-utc: true
This variable exists in other places in the V2 document, please remove, more quantity
Please conduct technical review
@lance6716 
> Remove the `skip-tz-utc` configuration item

- README.md
Hi, community!
To better present how our community grows, we develop a tool to show contributors growing history on [https://github.com/api7/contributor-graph](https://github.com/api7/contributor-graph). Since we found it helpful, we think maybe if it could help some other community.
Basically, it just shows the contributors growth over time, just like the stargazers over time on the README. It would be the same with stars that we would update the graph each day, so the link would always present the real-time data. There is some other stuff to play around with if you would like to give it a try~
We use Github API to get all commits, try to find the “Github way” to filter commits so the result data would be similar to Github, and then get the first commit time of each user.
Don't hesitate …
> feat: add contributor over time graph to README

- en/dmctl-introduction.md
- zh/dmctl-introduction.md
update dmctl doc to note that `master_addr` can be read from env var.
- This PR is translated from: https://github.com/pingcap/dm/pull/1726
> [2.0.4] dmctl: support read master addr from env

- en/TOC.md
- en/_index.md
- zh/TOC.md
- zh/_index.md
> update the index.md for 5.3

- en/_index.md
- en/deploy-a-dm-cluster-using-binary.md
- en/faq.md
- en/open-api.md
- en/releases/5.3.0.md
- zh/_index.md
- zh/deploy-a-dm-cluster-using-binary.md
- zh/faq.md
- zh/open-api.md
- zh/releases/5.3.0.md
changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
changed github.com/pingcap/ticdc to github.com/pingcap/tiflow
> changed github.com/pingcap/ticdc to github.com/pingcap/tiflow

- en/_index.md
- zh/_index.md
This PR tells users to go to TiDB documentation site to read DM documentation. 
> Add doc location change info of DM documentation

- en/shard-merge-best-practices.md
- zh/shard-merge-best-practices.md
1. Fix broken link in shard-merge-best-practices.md reported by https://github.com/pingcap/docs-dm/issues/898.
2. Fix a section that is missing in translation from https://github.com/pingcap/docs-dm/pull/698 to https://github.com/pingcap/docs-dm/pull/748
> Fix broken link in shard-merge-best-practices.md and addd a missing section

- .github/workflows/link.yaml
> ci: add link.yaml

- en/dm-manage-source.md
- en/dmctl-introduction.md
- zh/dm-manage-source.md
- zh/dmctl-introduction.md
Fix https://github.com/pingcap/docs-cn/issues/11439
- Other reference link(s): https://github.com/pingcap/docs-cn/pull/11441
> Remove the operate-source update command
